### ISSUE TITLE
迁移

### ISSUE THREAD

**Issue by Coffee-kitten** [cokemine/nodestatus#194]
在重新部署 迁移数据库之后登录web后台提示500错误，数据库类型是sqlite，尝试过重新拉取镜像也没用

**Comment by Coffee-kitten** [comment]
<details><summary>docker日志</summary>
<p>

#### log

```ruby
Error: secretOrPrivateKey must have a value

      at Object.sign$1 [as sign] (/app/packages/nodestatus-server/build/app.js:81631:20)

      at createSession (/app/packages/nodestatus-server/build/app.js:81800:23)

      at dispatch (/app/packages/nodestatus-server/build/app.js:14855:32)

      at /app/packages/nodestatus-server/build/app.js:60549:16

      at dispatch (/app/packages/nodestatus-server/build/app.js:14855:32)

      at /app/packages/nodestatus-server/build/app.js:14847:12

      at dispatch (/app/packages/nodestatus-server/build/app.js:60554:33)

      at dispatch (/app/packages/nodestatus-server/build/app.js:14855:32)

      at /app/packages/nodestatus-server/build/app.js:33630:14

      at dispatch (/app/packages/nodestatus-server/build/app.js:14855:32)        
```

</p>
</details>

**Comment by cokemine** [comment]
是从 [v1.1.0](https://github.com/cokemine/nodestatus/releases/tag/v1.1.0-alpha.6) 迁移到新版本的吗，如果是的话是一个破坏性的更新，之前的数据库文件没法用的

**Comment by Coffee-kitten** [comment]
> 是从 [v1.1.0](https://github.com/cokemine/nodestatus/releases/tag/v1.1.0-alpha.6) 迁移到新版本的吗，如果是的话是一个破坏性的更新，之前的数据库文件没法用的

不是 是之后的版本 监控是正常的

**Comment by cokemine** [comment]
> > 是从 [v1.1.0](https://github.com/cokemine/nodestatus/releases/tag/v1.1.0-alpha.6) 迁移到新版本的吗，如果是的话是一个破坏性的更新，之前的数据库文件没法用的
> 
> 不是 是之后的版本 监控是正常的

有设置 WEB_SECRET 这个环境变量吗

**Comment by Coffee-kitten** [comment]
> > > 是从 [v1.1.0](https://github.com/cokemine/nodestatus/releases/tag/v1.1.0-alpha.6) 迁移到新版本的吗，如果是的话是一个破坏性的更新，之前的数据库文件没法用的
> > 
> > 
> > 不是 是之后的版本 监控是正常的
> 
> 有设置 WEB_SECRET 这个环境变量吗

都是复制迁移前的配置的，存在这个变量但是没填，现在填了可以进了，看文档说不填和密码相同，以为跟这个无关😂

**Comment by cokemine** [comment]
扩展CLI选项之后这里不能为空字符串了，空字符串不会被默认值覆盖，而且不能作为jwt的secret会报错，还是修改一下比较好😂
